.github/pull_request_template.md
README.md
lib/CONTRIBUTING.md
lib/components/Page/Page.tsx

- feat: github icon in app
- doc: contributing and readme update
Adding more information in the doc before sharing github link

doc: readme, contributing, github icon

---

lib/components/Page/Page.tsx

- fix: help link uses github's issue creator
Now that the project is open source, the help link in the app will now redirect to github's issue creator

fix: help link to use github issue creator

---

lib/components/ContentEditable/ContentEditable.tsx

- fix: #42 
Adds style for images inside `ContentEditable` component

fix: #42 - Large images go over bounds of aspect

---

azure-pipelines.yml

- feat: enable azure devops deployment

feat: enable prod deployement

---

README.md
lib/components/Page/Page.tsx

- fix: remove netlify from footer

fix: remove netlify from footer

---

.eslintrc.json
CHANGELOG.md
lib/components/Page/Page.tsx
lib/routes/About/AboutRoute.tsx
lib/routes/ChangeLog/ChangeLogRoute.tsx
lib/routes/Play/PlayOfflineRoute.tsx
lib/routes/Play/PlayPage.tsx
lib/routes/Play/PlayRoute.tsx
lib/routes/Play/useScene/useScene.ts
lib/services/injections.ts
package.json

- feat: change log route
- feat: version in footer

feat: v2.2.2

---

lib/components/Kofi/Kofi.tsx

- fix: ko-fi exception when not available

feat: 2.3.1 (ko-fi exception)

---

lib/routes/Characters/CharacterDialog.tsx
lib/routes/Characters/hooks/__tests__/useCharacters.test.tsx
lib/routes/Characters/hooks/useCharacter.tsx
lib/routes/Characters/hooks/useCharacters.tsx

- feat: character stress box labels

feat: character stress box labels

---

CHANGELOG.md
azure-pipelines.yml
lib/contexts/CharactersContext.tsx
lib/routes/Characters/CharacterDialog.tsx
lib/routes/Characters/hooks/__tests__/useCharacter.test.tsx
lib/routes/Characters/hooks/useCharacter.tsx
lib/services/injections.ts
package.json

- fix: #76 Player loose modification to their characters in the dialog when a GM syncs a scene with them
- feat: turned on typescript incremental builds
- test: useCharacter syncs
- refac: character dialog logic inside useCharacter hook
- fix: use prod Fari peer server in prod

feat: v2.3.6 (faster build, fix character dialog sync, tests, prod peer-to-peer)

---

lib/routes/About/page/About.en.md
lib/routes/About/page/About.es.md

**docs** Minor capitalization fixes of GitHub 😊

chore: rename Github to GitHub

---

lib/blog/posts/2020-11-10-fari-3-3-0-groups-roll-skills.md
lib/components/ContentEditable/ContentEditable.tsx
lib/components/Page/Page.tsx
lib/routes/Home/HomeRoute.tsx

- feat: patreon in footer
- fix: lower delay for content editable changes + remove blug
Patch for 3.3.1

feat: v3.3.1 patch

---

lib/routes/Home/HomeRoute.tsx

- feat: add ryan singer to patreon list
New 9$ Patreon 🥳 

feat: v3.3.4.1 (add ryan singer patreon)

---

CHANGELOG.md
cypress/integration/route/Draw.spec.ts
lib/blog/posts/2020-12-07-fari-3-3-5-oracle.md
lib/components/DrawArea/DrawObjects.tsx
lib/components/DrawArea/hooks/useDrawing.ts
lib/routes/Character/components/CharacterDialog.tsx
lib/routes/Character/hooks/__tests__/useCharacter.test.tsx
lib/routes/Character/hooks/useCharacter.tsx
lib/routes/Oracle/OracleRoute.tsx
package.json

- doc: update
- fix: #170 
- fix: onStopDrawing now releases on touch end
- fix: setPointerCapture to handle out of boundary drawing
- fix: set touchAction: none to better handle mobile drawing
v3.3.5 release touchups

feat: v3.3.6 (release touchups)

---

CHANGELOG.md
cypress/integration/route/Home.spec.ts
cypress/lib/util/Fari.ts
lib/components/CookieConsent/CookieConsent.tsx
lib/components/Page/Page.tsx
lib/services/internationalization/locales/deTranslation.ts
lib/services/internationalization/locales/enTranslation.ts
lib/services/internationalization/locales/esTranslation.ts
lib/services/internationalization/locales/frTranslation.ts
lib/services/internationalization/locales/ptbrTranslations.ts
lib/services/internationalization/locales/ruTranslation.ts
package.json
yarn.lock

- feat: include Fate License for Core, Condensed and Accelerated
- feat: include link to privacy policy

feat: v3.3.8 (Fate license, privacy policy)

---

CHANGELOG.md
lib/components/CharactersManager/CharactersManager.tsx
lib/components/ContentEditable/ContentEditable.tsx
lib/components/Manager/Manager.tsx
lib/components/Page/Page.tsx
lib/components/Scene/Scene.tsx
lib/components/Scene/components/PlayerRow/CharacterCard/CharacterCard.tsx
lib/components/ScenesManager/ScenesManager.tsx
lib/contexts/CharactersContext/CharactersContext.tsx
lib/contexts/CharactersContext/__tests__/CharactersContext.test.tsx
lib/contexts/SceneContext/ScenesContext.tsx
lib/contexts/SceneContext/__tests__/useScenes.test.tsx
lib/domains/array/__tests__/arraySort.test.ts
lib/domains/array/arraySort.ts
lib/hooks/useBlockReload/useBlockReload.tsx
lib/hooks/useScene/__tests__/useScene.test.ts
lib/routes/Character/components/CharacterDialog.tsx
lib/routes/Play/JoinAGameRoute.tsx
lib/services/internationalization/locales/deTranslation.ts
lib/services/internationalization/locales/enTranslation.ts
lib/services/internationalization/locales/esTranslation.ts
lib/services/internationalization/locales/frTranslation.ts
lib/services/internationalization/locales/ptbrTranslations.ts
lib/services/internationalization/locales/ruTranslation.ts
lib/theme.tsx

- fix: block reload when playing a Scene [#178](https://github.com/fariapp/fari/issues/178)
- fix: sort button [#177](https://github.com/fariapp/fari/issues/177)
- feat: join a game using the Add or Import character buttons
- feat: scene name help text
- feat: basic print mode for character sheets

feat: v.3.3.9 (block scene reload, sort fix button, join game with new character)

---

CHANGELOG.md
lib/components/MagicGridContainer/MagicGridContainer.tsx
package.json

- fix: sentry errors with magic grid container

feat: v.3.3.10 (sentry errors magic grid container)

---

CHANGELOG.md
lib/components/Scene/Scene.tsx
lib/hooks/useScene/useScene.ts
lib/routes/Play/JoinAGameRoute.tsx
lib/routes/Play/PlayRoute.tsx
lib/routes/Play/types/IPeerActions.ts
package.json

- fix: loading character VS updating character
- fix: join screen explanation

feat: v3.4.2 (load character and join screen details)

---

lib/routes/SrdRoute/SrdRoute.tsx
lib/routes/SrdRoute/hooks/useMarkdownFile.tsx
package.json

feat: v3.4.6 (srd search)

---

lib/components/MarkdownElement/MarkdownElement.tsx
lib/components/Scene/components/PlayerRow/PlayerRow.tsx
lib/hooks/useLightBackground/useLightBackground.ts
lib/routes/SrdRoute/SrdRoute.tsx
lib/srds/fate-core.md
package.json

feat: v3.4.10 (markdown style)

---

lib/services/internationalization/locales/glTranslation.ts

Fixes a very small typo in the Galician translation.
It's quite a minor thing. No rush, release it whenever :)

Fix Galician typo

---

lib/App.tsx
lib/domains/character/CharacterFactory.tsx
lib/domains/character/CharacterType.tsx
lib/domains/character/character-templates/EdgeOfTheEmpire.json
lib/locale.ts
locales/en.json
locales/fr.json
stories/CharacterCard.stories.tsx
stories/CharacterSheet.stories.tsx

(Première pull request!!!) 
Au fond, j'ai ajouté le json pour le template de Edge, et j'ai modifié les différents fichiers en conséquence, en me servant de Maze comme référence (vu que c'est un jeu non-fate, et qu'ils n'ont pas l'air d'avoir la même structure). Donc ce sont de tout petits changements dans une dizaine de fichiers différents.
Fichiers de traduction : à noter que j'ai juste ajouté la référence vers la fiche dans les fichiers FR et EN, je ne sais pas si j'aurais dû le faire dans les autres versions? La fiche marche pareil si je change de langue, elle reste juste en anglais (on l'a juste faite en anglais pour le moment). Je pensais faire une version FR en trouvant une fiche officielle en ligne, cela dit, donc j'ai laissé la réf dans le fichier FR pour l'instant.
- J'ai fait …

feat: Edge of the Empire (ajout fiche + integration au code)

---

CHANGELOG.md
docs/fari-wiki.md
lib/App.tsx
lib/domains/character/CharacterFactory.tsx
lib/domains/character/CharacterType.tsx
lib/domains/character/character-templates/EdgeOfTheEmpire.json
lib/locale.ts
locales/en.json
locales/fr.json
package.json
stories/CharacterCard.stories.tsx
stories/CharacterSheet.stories.tsx

- fix: remove image tip from wiki
- feat: new Edge of the Empire template @Gpoitras

feat: 4.0.8 (wiki, star wars edge of the empire template)

---

lib/App.tsx
lib/domains/character/CharacterFactory.tsx
lib/domains/character/CharacterType.tsx
lib/domains/character/character-templates/EdgeOfTheEmpire.json
lib/domains/character/character-templates/EdgeOfTheEmpire_FR.json
lib/locale.ts
locales/en.json
locales/fr.json
stories/CharacterCard.stories.tsx
stories/CharacterSheet.stories.tsx

Added the French character sheet for Edge and updated the CharacterCard
- Tested everything on the Fari app and in the storybook. I still don't have a clue about automated testing, but basically I just changed a .json, so if this actually breaks something I'll be VERY confused x)

feat: Edge of the Empire : French sheet + storybook

---

lib/routes/StoryBuilder/hooks/Decks.tsx

Ennemey == Enemy
-fix for typo in story cards
simple typo fix

Update Decks.tsx to fix Typo

---

docs/fate-accelerated.md

- fix docs: remove bogus `<span>` element from fae srd mardown file
This issue made it impossible to view the Fate Accelerated SRD 
- after rebuilding thee fae srd html rebuiling using `npm run start:all` all works fine
The fixed section in SRD after rebuild

fix html parsing error in fate accelerated srd

---

docs/fari-wiki.md

Just correcting a couple of typos on the Getting Started > Playing page of the wiki.

Correcting typos in Getting Started > Playing.

---

lib/domains/character/CharacterFactory.tsx
package-lock.json
package.json

- fix: `default` prop in v4 character sheet templates
- fix: @dependabot build(deps): bump axios from 0.21.1 to 0.21.2 (#347) 
- fix: @dependabot build(deps): bump immer from 9.0.5 to 9.0.6 (#346)

feat: v5.3.1 (default in character sheet templates)

---

CHANGELOG.md
lib/constants/Delays.ts
lib/routes/Character/components/CharacterDialog/components/blocks/BlockDicePool.tsx
lib/routes/CharacterPrint/CharacterPrintRoute.tsx
package.json

- feat: collapsible dice pool controls

feat: v5.3.3 (collapsible dice pool controls)

---

cypress/integration/route/Characters.spec.ts
index.html
lib/components/PageMeta/PageMeta.tsx
lib/routes/Home/HomeRoute.tsx

feat: change app title to "Fari App"

feat: change app title

---

lib/components/MyBinder/MyBinder.tsx
lib/routes/Character/components/CharacterDialog/components/BlockByType.tsx
lib/routes/Character/components/CharacterDialog/components/blocks/BlockDicePool.tsx
package.json

feat: delete dead code

---

CHANGELOG.md
cypress/integration/route/Characters.spec.ts
cypress/integration/route/Scenes.spec.ts
lib/components/DiceFab/DiceMenu.tsx
lib/components/MyBinder/MyBinder.tsx
lib/components/Scene/components/PlayerRow/CharacterCard/CharacterCard.tsx
lib/locale.ts
lib/routes/Character/components/CharacterDialog/components/blocks/BlockDicePool.tsx
package-lock.json
package.json
public/locales/en/translation.json

- fix: binder overlapping info mobile
- fix: dice menu popper position in character sheet going out of bound 
- feat: always show dice menu options in advanced mode
- fix: block write view of dice pool blocks on character cards

feat: v5.3.5

---

lib/domains/character/CharacterFactory.tsx
lib/domains/character/CharacterType.tsx
lib/domains/character/character-templates/CortexKitchenSink.json
lib/domains/character/character-templates/FateCoreGerman.json
lib/domains/character/character-templates/TheWitchIsDead_FR.json
package.json

- feat: new CortexKitchenSink template
- feat: new TheWitchIsDead_FR template
- feat: new FateCore_DE template

feat: v5.3.6 (new templates)

---

lib/App.tsx
lib/contexts/DiceContext/DiceContext.tsx
package.json
stories/StoryProvider.tsx

fix: v6.0.8 (dice context options local storage)

---

lib/components/Scene/Scene.tsx
lib/routes/Play/PlayRoute.tsx
package.json

fix: character sync issues found by hunal#4866

fix: v6.2.6 (character card sync issues)

---

lib/domains/character/character-templates/Others/Mission Accomplished.json

BLOT: Character sheet template to support [Mission: Accomplished](https://www.drivethrurpg.com/product/300870/Mission-Accomplished)
I contributed this on the discord server the other day, but I wanted to get some experience contributing on Github and I thought it might be easier for a maintainer to review a PR than to add everything themselves, hence my contribution here :grin: 
This is a simple character template for [Mission: Accomplished](https://www.drivethrurpg.com/product/300870/Mission-Accomplished) games. I've formatted the JSON file as closely as I can to the other character sheets by inspection; please let me know if anything is amiss or needs further adjustment.
The JSON template uploads just fine to the live instance. I do not know if there are additional automated tests to …

feat: Add character sheet for 'Mission: Accomplished'

---

.github/workflows/ci.yml
lib/components/ContentEditable/ContentEditable.tsx
lib/components/IndexCard/IndexCard.tsx
lib/components/Scene/Scene.tsx
lib/components/Scene/components/PlayerRow/PlayerRow.tsx
lib/domains/cypress/types/IDataCyProps.tsx
lib/hooks/useEvents/useEvents.tsx
lib/routes/CardCollection/CardCollectionRoute.tsx
lib/routes/Character/components/CharacterDialog/CharacterV3Dialog.tsx
lib/routes/Character/components/CharacterDialog/components/BlockByType.tsx
lib/routes/Character/components/CharacterDialog/components/SheetHeader.tsx
lib/routes/Character/components/CharacterDialog/components/blocks/BlockDicePool.tsx
lib/routes/Character/components/CharacterDialog/components/blocks/BlockImage.tsx
lib/routes/Character/components/CharacterDialog/components/blocks/BlockInfoText.tsx
lib/routes/Character/components/CharacterDialog/components/blocks/BlockNumeric.tsx
lib/routes/Character/components/CharacterDialog/components/blocks/BlockPointCounter.tsx
lib/routes/Character/components/CharacterDialog/components/blocks/BlockSeparator.tsx
lib/routes/Character/components/CharacterDialog/components/blocks/BlockSlotTracker.tsx
lib/routes/Character/components/CharacterDialog/components/blocks/BlockText.tsx
lib/routes/Play/PlayRoute.tsx
lib/routes/Play/components/PlayersPresence/PlayersPresence.tsx
package-lock.json
package.json
stories/PlayerRow.stories.tsx
vite.config.ts

fix: performance issue that rerendered entire sessions on cursor move
fix: memoize <PlayerRow/> components to help performance

feat: v6.3.5 (fix performance issues)

---

lib/domains/character/character-templates/Dicey Tales RPG/Dicey Tales Hero.json

New Character Template
Notified by Andy'all on Discord of github file @ https://github.com/RoxvilleRooster/RoxvilleRooster.github.io/blob/master/dicey_tales/Dicey_Tales_Hero.fari.json
Verified locally

Create Dicey Tales Hero.json

---

lib/domains/character/character-templates/Dicey Tales RPG/Dicey Tales Hero.json

Pushing minor edit to force rebuild
-

Update Dicey Tales Hero.json

---

lib/domains/character/character-templates/Dicey Tales RPG/Barbarians of Lemuria Hero.json

New template for Barbarians of Lemuria
Notified on Discord
Uploaded Locally

Barbarians of Lemuria Template
