farirpgs/fari-app

.github/ISSUE_TEMPLATE/bug_report.md, lib/routes/Dice/DiceRoute.tsx, lib/routes/Play/components/PlayerRow.tsx
- fix: #35 dice rolling animation issue
Seems like emotion is having trouble properly updating the animation property when you are not focused on the tab that has an animated object.
I refactored the code to simply "remove" the css class when it needs to stop animating
=> fix: #35 dice rolling animation issue

lib/routes/Play/PlayRoute.tsx, lib/routes/Play/useScene/useScene.ts
- fix: Sentry issue FARI-11
It seems like when a player loses connection to the host, it certain cases the host might send an "empty scene" which crashes the rendering cycle.
This PR makes sure that it's not possible to set a scene has `undefined`
=> fix: sentry FARI-11

lib/domains/dice/Dice.ts
- **Fix**: Die rolls are now truly fair, and no longer slightly biased downwards.
This should resolve #56
=> fix: getting random die side now is truly fair based on the number of side

README.md, lib/components/DrawArea/DrawArea.tsx, lib/components/Page/Page.tsx, lib/routes/Play/PlayPage.tsx, lib/routes/Play/useScene/IScene.ts, lib/routes/Play/useScene/useScene.ts, lib/theme.tsx
- feat: new DrawArea component
- feat: used DrawArea in session
- feat: sync DrawArea using Peer to Peer
- style: bolder buttons
This PRs adds a new Drawing Area on Scenes where GMs can draw zones or else. Anything the GM draws is synced to the players using peer to peer communication
Closes #58 
=> feat: drawing component on scene

lib/components/CharactersManager/CharactersManager.tsx, lib/components/Manager/Manager.tsx, lib/components/Manager/domains/ListItem.ts, lib/components/ScenesManager/ScenesManager.tsx, lib/services/internationalization/locales/enTranslation.ts, lib/services/internationalization/locales/esTranslation.ts, lib/services/internationalization/locales/ptTranslation.ts
-**feat** Can now export scenes to a json file, to allow sharing it to other devices/individuals. 
-**feat** Can now export characters to a json file, to allow sharing it to other devices/individuals.
-**feat** Can now import scenes from a json file
-**feat** Can now import characters from a json file
Recently discovered this tool and so I'm planning on using it for an upcoming event. However I wanted an easier way to get my players all setup with their custom characters ahead of time. Saw the recent updates to allow for local saving, which got my thinking of an export/import feature for characters being possible. Once that was done, the scenes were an easy next step. 
- Made new character using existing features
- Exported character using new feature
- Made local edits to recently …
=> feat: import export scenes and characters

lib/components/DrawArea/DrawArea.tsx
- **feat** Switched out the mouse events for pointer event, allowing for touch controls on the drawable area.
When using the app on a touch screen device, instead of drawing on the draw area, it scrolls. This change allows for a more intuitive reaction on touch screen devices.
- Tested with a touch screen laptop and personal Android device. Seems to behave as I expect it should.
=> feat: touch support for DrawArea component

lib/contexts/CharactersContext/CharactersContext.tsx, lib/contexts/CharactersContext/__tests__/CharactersContext.test.tsx, lib/hooks/useScene/__tests__/useScene.test.ts, lib/hooks/useScene/useScene.ts
- fix: saving characters only if they exists
This PR fixes a pretty major issue I encountered yesterday while playing with the latest version with a couple of friends.
The issue is that when a player saves their character, the scene was calling a function to `update or insert` the character while it should have been using an `update only if exists` logic.
Because of this, it would cause everyone to have access to a copy of everyone's character. 
I think it's also part of the reason why we all ended up with 100 copies of someone's character.. (but I'm not 100% sure)
**Steps to reproduce**
* open two browsers
* create a session in the first browser
* create a character in the second browser
* copy the game link of the first browser
* join the session from the second browser with the created …
=> feat: v3.1.0 (upsert characters for everyone during play session)

CHANGELOG.md, lib/components/DrawArea/hooks/useDrawing.ts, lib/components/IndexCard/IndexCard.tsx, lib/components/MagicGridContainer/MagicGridContainer.tsx, lib/hooks/useMounted/useMounted.ts, package.json
- fix: disable setAspectDrawArea to stop default isDirty on scene load
- fix: add try-catch on useDrawing setPointerCapture for unsupported browsers
- fix: only reposition index card if component is mounted
This PR fixes a couple of errors I've seen hapenning on Sentry
=> fix: v.3.3.7 (scene dirty state, useDrawing.setpointerCapture exception, MagicGrid check isMounted)

lib/components/IndexCard/IndexCard.tsx
- feat: index card "has played" icon now has a tool tip, matching the similar button in player row
While trying out fari I found the has played button on the index cards and did not understand what it meant from the icon. I later saw the same button in player row and learned the meaning from the tool tip.
- I verified that the tool tip appeared by running the npc index card in storybook. I checked both has and has not played states
- I also verified in app on the scenes page for npcs and bad guys
=> feat:Index card "has played" icon now displays a tooltip

CHANGELOG.md, lib/components/DiceFab/DiceFab.tsx, lib/components/Scene/Scene.tsx, lib/contexts/DiceContext/DiceContext.tsx, lib/routes/Dice/DiceRoute.tsx, package.json
- fix: clicking the roll button when the dice menu is closed rerolls the latest rolled commands instead of the selected ones
> Not sure if this counts as a bug, but if I click out of the dice roller before rolling, and then roll, the roller will keep the previous dice input. This includes repeating previous skill rolls. You must roll while the dice menu is up in order to change the rolled dice. - Tolamaker
https://discord.com/channels/797926344893005875/798217992848146463/836041943196237894
When the dice menu is opened, everytime a user selects or deselects a dice command group, it saves it in the global context.
When a user rolled a set a dice commands, it saved that info as well so that you could "reroll" them but its not really a behavior we want anymore since dice commands arent …
=> feat: v4.0.7 (clicking roll button when dice menu is closed rolls latest rolled commands instead of new ones)

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, README.md
- feat: add devcontainer support for alternative development options
Devcontainer support will allow more contributions without a need for them to install specific versions of node/npm locally.
=> feat: Add devcontainer support for alternative development options

.github/workflows/ci.yml, lib/domains/character/CharacterFactory.tsx
**fix**
-
Duplicated and made from template characters are currently retaining Ids from their original sheets which is causing collisions. 
=> Regenerate nested Ids on character make and duplicate functions

lib/domains/character/character-templates/Cortex/Cortex Kitchen Sink.json
Copy Paste errors noted by Nugat on Discord
Edited the help text in the Cortex Kitchen Sink template
Nugat caught the mistake and mentioned it in Discord
=> Update Cortex Kitchen Sink.json

lib/components/IndexCard/IndexCard.tsx, lib/components/IndexCard/hooks/useIndexCard.tsx, lib/hooks/useScene/useScene.ts
- fix: #407
The Drag and Drop context needs an id to know where things can be dropped or not. In this case, when an index card was rendering the DnD context for sub cards it was using the id of the current card instead of the parent one.
I also added a check in the controllers to make sure to only move the cards if a card is found in the current array.
=> fix: index card drag and drop types

lib/routes/Draw/TldrawWriterAndReader.tsx
- fix: tab switching draw issue where data is not initialized
- fix: also hide the menu in readonly tldraw
Adding this line fixes the issue where the drawing is missing when you switch tab. The issue is that when you mount the drawing component, your shapeRef and bindingRef is not initialized with the old data 
- I tested my work on the feature environment [x]
=> fix: tab switching draw issue where data is not initialized

lib/components/IndexCard/IndexCard.tsx
Fix for: 
https://fari.app/bugs/p/promoted-subcards-have-no-mark-public-button
https://fari.app/bugs/p/cant-move-out-card
https://github.com/fariapp/fari-app/issues/410
Set .sub = false on move out
[
](https://fari.app/bugs/p/promoted-subcards-have-no-mark-public-button)
tested locally
=> Bug fix for Subcard

lib/routes/Play/components/CursorWithMessage/CursorWithMessage.tsx, lib/routes/Play/components/PlayersPresence/PlayersPresence.tsx
- fix: cursor chat box CSS scroll position
There was this weird [CSS bug](https://discord.com/channels/797926344893005875/917091152539295774/1020331457404731453) that seemed to cause the chat box to be rendered WAY below the cursor when a user was scrolling. I think this is due to some CSS positioning stacking up. This PR [should fix the issue](https://discord.com/channels/797926344893005875/917091152539295774/1020335114275799171)!
I've also rearranged the position of the cursor/chatbox so that it's a bit more accurate to the real position
=> fix: cursor scroll position on host

lib/components/ContentEditable/ContentEditable.tsx, lib/constants/Delays.ts, lib/routes/Character/hooks/useCharacter.tsx
fix: https://github.com/farirpgs/fari-app/issues/477
=> fix: content editable timeout bug

cypress/e2e/route/Oracle.cy.ts, lib/components/Page/NavLink.tsx, lib/routes/Character/components/CharacterDialog/components/CircleTextField.tsx, lib/routes/Home/HomeRoute.tsx
This SHOULD fix bug #414, in a way that doesn't look too bad.
- **refactor**: change the text display used for numeric text inputs.
Per bug #414, the prior version had a limit on how large the value in the field could be.
=> Revamp numeric text field

.github/workflows/ci.yml
- **fix**: This should fix the CI failing on forks.
I had noticed when fixing the issue of the cap on Numeric fields that the CI consistently failed. Looking from the build logs, I think the issue is that it looks for secrets related to the main repo in a way that seems hardcoded. This _should_ fix that particular issue.
=> Fix CI requiring original repo
